### ISSUE TITLE
My custom-made Keyboard + functional Mouse setup

### ISSUE THREAD

**Issue by Foxiravoc** [VFansss/mgs2-v-s-fix#111] opened 2020-03-11 19:50 UTC
Hello VFansss,

My decision to elaborate my own K+M solution stemmed from the fact that I wanted a good friend of mine to discover the Metal Gear universe, however he feels uncomfortable using controllers and swears by the K+M setup. So I had to find a solution to make it work despite the shortcomings of the default keyboard layout with no native mouse support.

I made sure the keyboard layout + optional mouse input solution maximize the gameplay effectiveness while maintaining comfort for standard K+M setups. The reasoning behind my control layout is that one must be able to perform all combination of actions without affecting the movement controls (WASD) as to optimize the flow of the gameplay. 

You could either download the attached modified kb/kbs.ini files (key map included) or you could copy-paste the following fully functional desktop/laptop-friendly keyboard layout text and check my key map here: https://i.imgur.com/FCOSDzp.png

W U
A L
S D
D R
F Y
LMENU Y
Q L1
E R1
U L1
O R1
NUMPAD4 L1
NUMPAD6 R1
C EX1
J X
I B
L EX2
NUMPAD1 X
NUMPAD5 B
NUMPAD3 EX2
LSHIFT EX3
LCONTROL A
RCONTROL AR
SPACE L2
TAB SEL
RETURN STA
UP RU
DOWN RD
RIGHT RR
LEFT RL

The optional mouse input adds a level of comfort by binding some of the keyboard inputs to your mouse as to become a sort of secondary keyboard since native mouse support is non-existent. The mouse regroups all the combat related functions (punch, firearms, katana) and includes an emulated Right controller Stick (RS) with the mouse movement axes (very convenient for later on in the game :D) as well as the "EX2" function (pressure sensitive function). However, in order to make that work requires some tinkering but nothing complicated if you follow the instructions of my video tutorial: https://youtu.be/wCewMVlFFBQ

Hopefully this will help those who prefer to play with K+M enjoy MGS2.

If you find my solution helpful, feel free to share it.

P.S.: I appreciate the tremendous work you have done to make and keep the legacy alive. "Keep up the fine work, Sir!" :D
[kb-key_map.zip](https://github.com/VFansss/mgs2-v-s-fix/files/4339169/kb-key_map.zip)

**Comment by VFansss** [comment] 2020-03-16 09:36
Hi there!

Sorry for the very late reply: I had some hellish week...

Before everything: thanks for all your work!

I'm not so confident that MGS2 will ever be perfectly playable with kb+mouse, but everything that come close to that is always welcomed.

In the next version of the fix ("in progress" for a long time... I think too much) I planned to include some kb+m default layouts "ready to play".

I didn't tried yours, but I would like to see how well its playing...

The keyboard layout text is very cool. Maybe I will borrow the idea in the future!

> However, in order to make that work requires some tinkering but nothing complicated if you follow the instructions of my video tutorial: 

The issue is this: I've tried to design the fix trying to use less external software as possible.

There are 2 main reasons:

1. Copyright - I can't simply embed or distribute any software I want with my fix. In case of UCR, isn't an issue, because is MIT Licensed
2. Simplicity - A LOT of things can go wrong, with the potentially infinite combination of hardware and software available. I think the fix is working good overall, but I can't count anymore all messages for all various incompatibility I've received (and I will receive in the future). I've tried to use less external software as possible because each one simply add a 'complexity order' in possible disaster that could happen (and they happen, trust me) with every config.

After saying this, I don't think I will ever implement UCR inside the fix but I will try (if you want) to re-organize all your work inside the Wiki, or if I find a way to add it directly inside the fix in some way.

Thanks for all your work!

**Comment by Foxiravoc** [comment] 2020-03-16 13:13
Hello!

I hope you are doing well.

> The issue is this: I've tried to design the fix trying to use less external software as possible.

I'm aware of that inconvenience, that is why I made sure it is completely playable on the keyboard and included the mouse input as optional. Something I forgot to mention is that the reason why I assigned additional Item/Weapon menus to U, O or NUMPAD4, NUMPAD6 besides the A, E is to allow you to approach walls at any direction and still be able to perform the corner peek with these additional menus without taking your hands off the movement keys (W,A,S,D).

> After saying this, I don't think I will ever implement UCR inside the fix but I will try (if you want) to re-organize all your work inside the Wiki, or if I find a way to add it directly inside the fix in some way.

Your call. If you believe my solution, after trying it, improves the overall playability, then feel free to do whatever you want with it. :)

**Comment by Foxiravoc** [comment] 2020-03-16 16:39
Edit: I just rearranged and updated my post for the keyboard layout by assigning the "Action" function to "Left ALT" (LMENU Y) besides the "F key" (F Y), because I found that having Left ALT key is useful to perform the ledge hanging action when you are against the handrail or running towards it without sacrificing that WASD philosophy. :)

**Comment by VFansss** [comment] 2020-08-20 08:45
With the new version of the fix, I made it easier to install an external keyboard layout.

I didn't included directly inside the fix (I can't) but should be much better now.

[I've updated the Wiki](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#playing-with-keyboardmouse) with the download link, the instructions, a brief description and the key map.

I'm closing here, but you can always reopen the issue if there are update on topic.

Thanks again for everything (the key map and the video are well made, congrats) 👍

**Closed by VFansss** 2020-08-20 08:45 UTC
Labels: Input related, enhancement
