### ISSUE TITLE
Issue with DirectInput translation.

### ISSUE THREAD

**Issue by Lion4K** [VFansss/mgs2-v-s-fix#58] opened 2018-10-31 01:49 UTC
Boss, I'm having a big issue here with the translation from Dinput to Xinput.

Actually not really with the translation, it went fine, the big issue is that the game is both listening from dinput strokes as well xinput ones.

For instance, Button 8, it's acting as Start, but Start is also Start (keycode 12) .
Button 10 is acting as Katana poke, but also R-Stick as it should (keycode 15).

I am using InputMapper software, I was able to add my Dinput controller to it, set it up, XinputTest.exe recognize all keys as it should, so I got a perfectly fine xbox 360 controller plugged it (well at least for all intents), I've even tested on an other game and it worked.
All leads me to believe its in the MGS2 the issue, IDK what to do, I first thought of using the Dinput straight in the game, as it was once supposed to support it, but I can't find a way to map the dinput keys on the game directly.

So if you could help me by either instructing me on how to turn off the dinput part on the game, or the xinput part and mapping the dinput keys straight on the game, I would be really grateful.

Thank You Boss!!

**Comment by VFansss** [comment] 2018-10-31 10:45
Just for curiosity: what gamepad are you using?

> All leads me to believe its in the MGS2 the issue

Not exactly: I think that you Dinput->Xinput translator isn't actually "eating" the Dinput input, allowing for double keystrokes,

> So if you could help me by either instructing me on how to turn off the dinput part on the game

Not possible, I think

> or the xinput part and mapping the dinput keys straight on the game

The issue with this solution is that both layouts (V's and Ps2) are designed to work with certain button numbers of certain gamepads.

In xbox gamepad, button 4 is A. With other gamepads, this isn't absolutely certain.

So using another kind of gamepad (like a ps2, a xiaomi, or whatever you want) probably has different number buttons, thus invalidating all the work I've done to create two layouts.

> I am using InputMapper software

I never used it, so I can't directly say it, but you should try more tested solutions [like the two I mentioned in the wiki](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#none-of-the-above).

Using one of them should solve the issue.

**Comment by Lion4K** [comment] 2018-10-31 22:41
Thank you boss!

Its an Ipega 9021 bluetooth controller.
My usb ports are busted, I could if possible use my x360 controller or even plug the usb on the ipega (when in usb mode it gets recognized as a native xinput, idk why).

I'm gonna try using the original configurator as you instructed me.

Thansk again boss!

PS: Im drunk sorry for grammar

**Comment by digaoqueiroz** [comment] 2018-11-03 18:38
I'm with the same problem (same gamepad too). Did this fix work for you?

**Comment by VFansss** [comment] 2018-11-05 16:22
You could try this solution:

* Use X360CE, your 'InputMapper software' (what it is? can you link it to me?) or Xoutput, or any Dinput-Xinput converter.
* Open the fix, select OPTION, enable XBOX Controller (select the layout you want) and then SAVE.
* Extract the .ini contained in this .zip ---> [XInputPlus ipega.zip](https://github.com/VFansss/mgs2-v-s-fix/files/2549529/XInputPlus.ipega.zip) in the game folder.

**Comment by VFansss** [comment] 2018-12-27 18:33
I've tried some old xinput gamepad using Xoutput and, after configuring them properly, they are working as intended. One of them has even the vibration working!

I can't properly say that there is something I still can do, aside update the Wiki with more details on how to install Xoutput and Vigem, so I'm closing this issue 😢 

If there is still something I can do, please tell me and we will figure it out 😄

**Closed by VFansss** 2018-12-27 18:33 UTC
Labels: Gamepads related
