### ISSUE TITLE
V's Fix set wrong folder permissions to game folders for 'Everyone' user

### ISSUE THREAD

**Issue by El-Hack** [VFansss/mgs2-v-s-fix#41] opened 2018-06-14 18:10 UTC
So yeah every time i press the start button, the screen goes black for a few seconds and then game closes, i tried fixing it with the suggestions in the other issues posts here but nothing works and i have no idea how to activate the debug mode....

**Comment by VFansss** [comment] 2018-06-14 18:22
> So yeah every time i press the start button

So you are launching the game through the launcher, then the game windows open and it close itself automatically after few seconds, am I right?

> how to activate the debug mode

Its simple: close the Fix, then just create a file called "debug.sss" inside the "GAME DIRECTORY/bin" folder: its exactly the same location where you pasted the V's Fix.

The simply start the fix (you will also see a debug message on the screen when you are on debug mode), then please press SETTINGS, and then SAVE. Then simply start the game and let it crash.

After you finished that, send me these files 😃 :

* MGS2_VFix_debug.txt, that is on your desktop
* last.log, that is inside the game folder (where you created the debug.sss file)

**Comment by El-Hack** [comment] 2018-06-14 18:29
[last.log](https://github.com/VFansss/mgs2-v-s-fix/files/2103569/last.log)
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2103571/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment] 2018-06-14 19:27
Ok, I've pinpointed the cause of this issue. Honestly it was a pretty serious bug, so thank for reporting it 😄 

I have to release a new mini-version of the fix, because I think this is the cause of several other issues.

You could solve it manually before waiting for an official fix release, but I prefer to avoid you to mess with folders permissions.

I will release shortly ( = few hours) a new subversion of the fix, that should solve this issue.

Until then, please wait 😄

**Comment by El-Hack** [comment] 2018-06-14 19:33
Oh wow, welp thanks then, i will wait for the new version so i can finally play mgs2, thanks a lot

**Comment by VFansss** [comment] 2018-06-14 19:57
Ok. Hopefully now all is in its own place!

Please download the new fix, copy it inside the game folder, open it and press SAVE.

It should solve everything on its own.

Please confirm me that 😄

**Comment by El-Hack** [comment] 2018-06-14 21:41
Its still crashing..

**Comment by VFansss** [comment] 2018-06-14 21:42
Please send me again the last.log and MGS2_VFix_debug.txt

**Comment by El-Hack** [comment] 2018-06-14 21:46
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2104107/MGS2_VFix_debug.txt)
Umm the last log is gone

**Comment by El-Hack** [comment] 2018-06-14 21:51
ah i found the last log but its empty

**Comment by VFansss** [comment] 2018-06-14 21:55
Ok. This can be tough, so pay attention:

* Go to the game folder
* Go to the parent folder (Metal Gear Solid Substance 2)
* Select the 'bin' folder and press on it with the right mouse
    * Select "Properties"
* Go to the "Security" tab
* On the middle of the window, press the "EDIT" button
* Click on the "Everyone" user on top
* Send me a screenshot of what you got on screen

I've made a gif to simplify these steps. My system language is in italian, but the steps should be very easy to understand:

![tuto1](https://user-images.githubusercontent.com/15073502/41440302-56d05776-702e-11e8-8158-a3422ffc14d3.gif)

Sorry for all these issues, but I need to understand precisely what is causing this problem.

**Comment by El-Hack** [comment] 2018-06-14 22:00
![issues1](https://user-images.githubusercontent.com/40275624/41440492-afa51a8a-6ffc-11e8-90ac-2850196c3c26.png)
![issues2](https://user-images.githubusercontent.com/40275624/41440495-b109b502-6ffc-11e8-926a-f6966559e1a4.png)
Well my system is in spanish but i guess you can make out whats what

**Comment by VFansss** [comment] 2018-06-14 22:14
Ok, fantastic screenshots ❗️ 

Download the new version (the 1.05.2) and let's see if is working.

As usual: download -> copy to folder -> open it and press SAVE -> try to start the game

**Comment by El-Hack** [comment] 2018-06-14 22:18
And it crashed again.... maybe i have to do something with those folder perms or some?
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2104193/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment] 2018-06-14 22:21
Oh god 💀 

For now just check this box:

![41440492-afa51a8a-6ffc-11e8-90ac-2850196c3c26](https://user-images.githubusercontent.com/15073502/41441203-f0b09664-7031-11e8-8b50-4f8da0f9ff4f.png)

Tomorrow I will investigate better these issues, or I will completely revert the permission assignments.

Let me know if its working...

**Comment by El-Hack** [comment] 2018-06-14 22:31
when i applied the perms, it appeared a bunch of pop ups saying that various of the files had access denied or something and i tried opening the fix again anddd it crashed once again... maybe i have to reinstall everything? or idk at this point

**Comment by VFansss** [comment] 2018-06-14 22:34
Yes: unistall the game through the control panel, then manually delete the KONAMI folder inside Program Files (for purge everything left on the disk).

Then reinstall the game and retry with the 1.05.2 version of the fix.

If EVEN then it doesn't work...tomorrow I will revert something back, release the 1.05.3 version and solve once for all this mess...

Thanks for your patience :)

**Comment by El-Hack** [comment] 2018-06-14 22:36
Alright man and thanks to you also for helping me, ill try deleting everything now and reinstalling, i hope it works

**Comment by El-Hack** [comment] 2018-06-14 22:59
OK it didn't worked guess i'll wait for tomorrow

**Comment by VFansss** [comment] 2018-06-15 07:31
Ok. Just do another test: please unistall the game and reinstall it on another location (ES: C:\\Konami\Metal Gear Solid Substance 2\).

Then apply again the 1.05.2 Fix and, just like you done previously, press SAVE and then test is everything is working. Send me again the permission screenshots and the last.log and MGS2_VFix_debug.txt!

If that doesn't working too I have a new release to...release that will fix it!

**Comment by El-Hack** [comment] 2018-06-15 17:22
And once again it crashed and for some odd reason no matter how many times i unistall the game and reinstall it and then activating the debug mode, the last log just wont appear...
![issues part 2](https://user-images.githubusercontent.com/40275624/41481215-24c3a050-709f-11e8-8dec-769968621ee0.png)
![issues the issuening](https://user-images.githubusercontent.com/40275624/41481220-26d20d78-709f-11e8-8b55-dad718f3a53e.png)
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2106939/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment] 2018-06-16 17:15
Sorry but today was a hellish day...

Honestly this issues is make me going crazy.

Try this new rev: [MGS2SSetup_1806161914.zip](https://github.com/VFansss/mgs2-v-s-fix/files/2108363/MGS2SSetup_1806161914.zip)

Also, you can try to make an additional test: delete the "d3d8.dll" that you find inside the main game folder.

**Comment by El-Hack** [comment] 2018-06-16 18:49
Holy crap, deleting d3d8.dll and starting the game directly actually worked, wow man didn't even need to use the new rev, thank you :,)

**Comment by VFansss** [comment] 2018-06-16 18:52
Deleting the d3d8.dll will disable the widescreen fix, so this isn't actually a solution.

So this mean that your game doesn't start because another reason, aside the wrong permission bug that you made me discover previously.

**Comment by El-Hack** [comment] 2018-06-16 19:01
Maybe cuz its a laptop? not a bad one but also not the best, but i dont really see any issues with the game, i'm already playing

**Comment by VFansss** [comment] 2018-06-16 19:09
I developed the fix on my laptop too, so isn't that the issue.

> i dont really see any issues with the game, 

Well, probably the widescreenfix isn't currently running, so the game will be stretched.

Press again the SAVE button and the fix will copy again the fix, causing another hang-up.

Unfortunately the wrapper isn't done by me, so its pretty hard to understand what is causing this mess...

I will find something as soon as I can...

**Comment by VFansss** [comment] 2018-07-24 13:46
I think I've found the culprit.

Please re-download the 1.05.2 version from [HERE](https://github.com/VFansss/mgs2-v-s-fix/releases/download/v1.05.2/_OLD_v1.05.2.zip). Install it as usual.

Then select mgs2_sse.exe, click on it with the right mouse click, select PROPERTIES, go to compatibility and check the "Windows XP SP3" compatibility setting and the 'Start with admin rights" box?

![immagine](https://user-images.githubusercontent.com/15073502/43142046-c5295554-8f57-11e8-9ac4-e81ff345d201.png)

This should solve every issues, and you can enable the WS Fix without deleting anything at the same time.

If you could test this I would be very happy! 😄

**Comment by VFansss** [comment] 2018-08-04 16:34
Well, even without a test I'm sure that the permission "bug" is fixed.

The black screen issue was a separate things, and has been fixed in the last build of the fix.

Cheers!

**Closed by VFansss** 2018-08-04 16:34 UTC
Labels: bug
