### ISSUE TITLE
Xbox One Controller - Can't Grab / Choke?

### ISSUE THREAD

**Issue by illegalmp3** [VFansss/mgs2-v-s-fix#44] opened 2018-06-29 18:47 UTC
Hi there.

First off, thank you for all the work you've done getting MGS2 playable on the PC once again.  Thanks to your fixes, I'm running the game at a beautiful resolution, nice and smooth.  However, I seem to be having an issue with the controls.

I'm currently playing with an Xbox One controller, connected via USB on a Windows 10 laptop (Surface Book 2), and under your settings menu, I've chosen the Xbox Controller option along with the PS2 control scheme.  Upon starting the game, everything seems to be running perfectly.  However, when Snake is standing still and I put away my tranquilizer gun, the X button on my Xbox One controller (which would be the Square button on a PS2 controller) does not do anything.  I have not played MGS2 in years, but I believe Snake is supposed to execute a grab/flip/choke move when you press Square?  Instead, nothing happens no matter how many times I press the button - he just stands there.

Even more strange is that I can successfully shoot my tranquilizer gun using that same button, and I can even pick enemies up off the floor when they fall asleep - but I can't grab them from behind when they're standing.  It's as if grab/choke/flip are not mapped to the proper button, but everything else is.  I have no idea if I am not remembering the game correctly or if the controls are indeed not mapped correctly, haha.

Hoping this can be resolved easily and quickly.  Thanks again for all your hard work.

**Comment by illegalmp3** [comment] 2018-07-07 03:39
Hey!  My apologies for the late reply - I was out of town for a bit, but I did just unfortunately find out that the 1.04 version does not fix my problem with not being able to choke using X.  I did just acquire a PS4 controller, but it seems 1.05.2 is no longer available! :P  Let me know if there's anything I can do to help.  Thanks!

**Comment by VFansss** [comment] 2018-07-10 07:50
Sorry for the late reply!

> I did just acquire a PS4 controller, but it seems 1.05.2 is no longer available!

Is no longer available because it have serious issues on the graphical part of the fix.

I'm in serious trouble resolving them, and this is really hellish week 💀 

I will try to release again the 1.05 fix as soon as I'm sure that is working good as intended...

**Comment by VFansss** [comment] 2018-08-04 16:40
The 1.06 is coming, and should solve every issue.

At least I hope 😃

**Closed by VFansss** 2018-08-04 16:40 UTC
