### ISSUE TITLE
MGS2 can't save in "My games" folder

### ISSUE THREAD

**Issue by kintropy** [VFansss/mgs2-v-s-fix#142] opened 2020-10-04 08:00 UTC
Hello,

I love the fix but I can't save at all. Any attempt ends up saving to the drive I installed the game on (I keep my games and boot drive separate) I've tried everything on the guide and nothing has worked. Attached is the debug log and another stub log in my file. I'll also attach a save file in case there's something wrong with it( you'll have to convert this back to a save file, sorry github doesn't support it)
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/5322830/MGS2_VFix_debug.txt)
[stub.log](https://github.com/VFansss/mgs2-v-s-fix/files/5322831/stub.log)
[bHTjeMhwHwBWoBvdaIb7FZirx4FbcAhHJXqQL.txt](https://github.com/VFansss/mgs2-v-s-fix/files/5322833/bHTjeMhwHwBWoBvdaIb7FZirx4FbcAhHJXqQL.txt)

**Comment by VFansss** [comment] 2020-10-04 09:57
Have you follower [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix)?

Aside this:

> I love the fix but I can't save at all.

What do you mean? You can't save from the game, or you can save but then you save file 'disappear'?

> Any attempt ends up saving to the drive I installed the game on 

Can you please expand this part?

That you will find your savegames into the original "savedata" folder?

**Comment by kintropy** [comment] 2020-10-04 10:21
> Have you follower [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix)?
 Yeah I tried this
> Aside this:
> 
> > I love the fix but I can't save at all.
> 
> What do you mean? You can't save from the game, or you can save but then you save file 'disappear'?
  When I try to save it says the file saved but I can't load them. they don't even appear on "load game"
> > Any attempt ends up saving to the drive I installed the game on
> 
> Can you please expand this part?
  Yeah I don't find them in the original "savedata" folder and I do find these files on just the drive (like the path is just G:/) with a ".d" extension. I'm not sure if the way it was named the right way either. That's why I attached one of those files.

**Comment by kintropy** [comment] 2020-10-04 10:22
woops sorry the formatting on the comment was weird.

**Comment by kintropy** [comment] 2020-10-04 16:49
> Have you follower [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix)?
> 
Yes I have
> Aside this:
> 
> > I love the fix but I can't save at all.
> 
> What do you mean? You can't save from the game, or you can save but then you save file 'disappear'?
> 
When I try to save it says the file saved but I can't load them. they don't even appear on "load game"
> > Any attempt ends up saving to the drive I installed the game on
> 
> Can you please expand this part?
> 
Yeah I don't find them in the original "savedata" folder and I do find these files on just the drive (like the path is just G:/) with a ".d" extension. I'm not sure if the way it was named the right way either. That's why I attached one of those files.
> That you will find your savegames into the original "savedata" folder?
No I don't 

this is the updated comment

**Comment by kintropy** [comment] 2020-10-04 17:03
Ok tried a clean install again and I noticed that it simply won't create a folder or write to the "My Games" folder

**Comment by kintropy** [comment] 2020-10-04 17:36
Now I created a "METAL GEAR SOLID 2 SUBSTANCE" folder in "My Games" and the game acknowledges it but can not write in it.

**Comment by kintropy** [comment] 2020-10-05 11:35
Have you seen anything like this before?

**Comment by kintropy** [comment] 2020-10-05 11:44
Here are some of the error messages I get when trying to save:
"GetProcAddress: EXCEPTION module=GetProxyDllInfo Failed to get address. Code=c0000005
GetProcAddress: Could not find GetProxyDllInfo."
"X2W_ErrorPrintfID:ID 8"
[last.log](https://github.com/VFansss/mgs2-v-s-fix/files/5327102/last.log)

**Comment by kintropy** [comment] 2020-10-05 15:46
I'm using the gog version as well btw

**Comment by VFansss** [comment] 2020-10-06 10:14
Before all: sorry for the VERY late reply.

Here's what I think about the question:

* The game can't actually access to "My documents\My Games\METAL GEAR SOLID 2 SUBSTANCE" and every write to it is automatically redirected to main SO drive (thus why you find your savegames in that directory)

Why this happen? I have few theories, but I can't confirm none.

Until I try some kind of fix, you can try this:

* Go to "My Documents\My Games\METAL GEAR SOLID 2 SUBSTANCE" and DELETE the "METAL GEAR SOLID 2 SUBSTANCE" folder.

* Manually create the folder called "METAL GEAR SOLID 2 SUBSTANCE".

* Check if permission on it are right.

  * Right click on "METAL GEAR SOLID 2 SUBSTANCE" folder, choose "Properties"
  * Go to "Security" tab
  * Check if you user has every permission (my user is called "Alex DG")

![immagine](https://user-images.githubusercontent.com/15073502/95188595-ef090280-07cc-11eb-85d0-1c255fdacb08.png)

  (If you can, post me a screenshot of what you have there, just for curiosity)

  * Run the game DIRECTLY from "mgs2_sse.exe" (don't use V's fix launcher)

Try to see if you can save and load your savegame correctly, and see if the folder is correctly populated by your savegames.

I'm sorry for all these troubles, but this seems an old issue that once in a while pop up and I can't certainly pinpoint what's the cause.

I know that this is annoying, but try to follow what I wrote and send me the results, so I could solve this once for all 😄

**Comment by kintropy** [comment] 2020-10-06 10:42
> Before all: sorry for the VERY late reply.
> 
> Here's what I think about the question:
> 
> * The game can't actually access to "My documents\My Games\METAL GEAR SOLID 2 SUBSTANCE" and every write to it is automatically redirected to main SO drive (thus why you find your savegames in that directory)
> 
> Why this happen? I have few theories, but I can't confirm none.
> 
> Until I try some kind of fix, you can try this:
> 
> * Go to "My Documents\My Games\METAL GEAR SOLID 2 SUBSTANCE" and DELETE the "METAL GEAR SOLID 2 SUBSTANCE" folder.
> * Manually create the folder called "METAL GEAR SOLID 2 SUBSTANCE".
> * Check if permission on it are right.
>   
>   * Right click on "METAL GEAR SOLID 2 SUBSTANCE" folder, choose "Properties"
>   * Go to "Security" tab
>   * Check if you user has every permission (my user is called "Alex DG")
> 
> ![immagine](https://user-images.githubusercontent.com/15073502/95188595-ef090280-07cc-11eb-85d0-1c255fdacb08.png)
> 
> (If you can, post me a screenshot of what you have there, just for curiosity)
> 
> * Run the game DIRECTLY from "mgs2_sse.exe" (don't use V's fix launcher)
> 
> Try to see if you can save and load your savegame correctly, and see if the folder is correctly populated by your savegames.
> 
> I'm sorry for all these troubles, but this seems an old issue that once in a while pop up and I can't certainly pinpoint what's the cause.
> 
> I know that this is annoying, but try to follow what I wrote and send me the results, so I could solve this once for all 😄

It's cool about the annoying part. I did all this and I created a save before installing the patch this time to see if the file would move properly. The file actually did and it can load just fine, but when I try to save again after the patch it now says "save failed" instead of creating a new save. My user and administrator have full access (I'm careful about posting screenshots from my pc, especially if it comes to user information, sorry). launching directly yielded the same results.

**Comment by kintropy** [comment] 2020-10-06 18:35
Putting the game in my primary driver didn't work either

**Comment by kintropy** [comment] 2020-10-07 15:13
I can manually create a folder in the "My Games" path and putting saves there works but they can not be overwritten. and if I don't have a save file for the main game. the game says it saved successfully but I just find them in the G:/ directory

**Comment by kintropy** [comment] 2020-10-07 15:40
If I the game on my main C:\ drive I get a similar result with the save going to C:\ instead

**Comment by kintropy** [comment] 2020-10-07 16:59
I SOLVED IT. The "My Games" folder has protected access so you need to allow "mgs2_sss.exe" through.

**Comment by kintropy** [comment] 2020-10-07 17:04
Windows defender will automatically block apps it does not recognize from protected folder access but you can add exceptions in "App & Browser Control" then goin to "Reputation-based protection" and "Protection history" and if you filter "Blocked folder access" you can find the exe and set it up as an exception.

**Comment by VFansss** [comment] 2020-10-10 08:47
Before all: sorry for the late reply.

I truly appreciate your investigation, and I will keep into consideration for understanding how to solve this issue once for all.

Unfortunately, you basically done a lot of experiment aside what I had in mind to do, thus now I'm not sure how to make you test the situation with precision.

> Putting the game in my primary driver didn't work either.

100% is not the issue

> I also made sure the game was let through my firewall just in case that somehow affected it.

Game neither the fix require firewall permissions of any kind

> I can manually create a folder in the "My Games" path and putting saves there works but they can not be overwritten. and if I don't have a save file for the main game. the game says it saved successfully but I just find them in the G:/ directory
> If I the game on my main C:\ drive I get a similar result with the save going to C:\ instead

This happen because game can't find the save directory (inside "My games") and somehow Windows redirect its saving location to the root of the disk. Instead, if the directory actually exist but it doesn't have access right, it make "ghost" saves.

The whole issue (IMHO) is caused by some kind of but in the creation of the "METAL GEAR SOLID 2 SUBSTANCE" folder inside "My Games".

**Did you usually start the game pressing "Launch game" from withing the V's fix?**

**Is "METAL GEAR SOLID 2 SUBSTANCE" the only folder you have inside "My Games" folder in My Document? (aka: did the game create "My Games" folder or it has already existing before installing/launching the game?**

> I SOLVED IT. The "My Games" folder has protected access so you need to allow "mgs2_sss.exe" through.

Can you make a screenshot of what you have done? I'm having hard time figuring what actions you performed.

**Comment by kintropy** [comment] 2020-10-11 19:33
> Before all: sorry for the late reply.
> 
> I truly appreciate your investigation, and I will keep into consideration for understanding how to solve this issue once for all.
> 
> Unfortunately, you basically done a lot of experiment aside what I had in mind to do, thus now I'm not sure how to make you test the situation with precision.
> 
> > Putting the game in my primary driver didn't work either.
> 
> 100% is not the issue
> 
> > I also made sure the game was let through my firewall just in case that somehow affected it.
> 
> Game neither the fix require firewall permissions of any kind
> 
> > I can manually create a folder in the "My Games" path and putting saves there works but they can not be overwritten. and if I don't have a save file for the main game. the game says it saved successfully but I just find them in the G:/ directory
> > If I the game on my main C:\ drive I get a similar result with the save going to C:\ instead
> 
> This happen because game can't find the save directory (inside "My games") and somehow Windows redirect its saving location to the root of the disk. Instead, if the directory actually exist but it doesn't have access right, it make "ghost" saves.
> 
> The whole issue (IMHO) is caused by some kind of but in the creation of the "METAL GEAR SOLID 2 SUBSTANCE" folder inside "My Games".
> 
> **Did you usually start the game pressing "Launch game" from withing the V's fix?**
> 
> **Is "METAL GEAR SOLID 2 SUBSTANCE" the only folder you have inside "My Games" folder in My Document? (aka: did the game create "My Games" folder or it has already existing before installing/launching the game?**
> 
> > I SOLVED IT. The "My Games" folder has protected access so you need to allow "mgs2_sss.exe" through.
> 
> Can you make a screenshot of what you have done? I'm having hard time figuring what actions you performed.

Yeah sorry I will post them in a couple days

**Comment by kintropy** [comment] 2020-10-19 03:58
First go to your security settings
![image](https://user-images.githubusercontent.com/10376749/96399918-5be4ab00-1184-11eb-9e4c-66eb5c044e84.png)
then go to app and browser control
![image](https://user-images.githubusercontent.com/10376749/96399963-77e84c80-1184-11eb-9efa-710ba2c29b94.png)
then reputation based settings
![image](https://user-images.githubusercontent.com/10376749/96400015-90f0fd80-1184-11eb-862c-06ff89b111f2.png)
then just turn off what I have there, or you can keep it on and let the mgs2 game exe through the system

**Comment by kintropy** [comment] 2020-10-19 09:50
I assume you can use admin permission given to your setup program to send a command that sets mgs2 as safe

**Comment by kintropy** [comment] 2020-10-29 20:39
Did this clear things up?

**Comment by kintropy** [comment] 2020-11-23 01:17
It alright if I close this issue?

**Comment by VFansss** [comment] 2020-11-23 07:45
I know that I've been a bad guy, but I didn't answered not because I didn't appreciated your investigation, but simply because I didn't had the time to wrap everything into an action plan, yet :(

I'm very busy and tired lately, and I didn't had the time to think about how to solve this.

I will close this issue when I make the right things to solve this once for all 😄

**Comment by kintropy** [comment] 2020-11-28 11:44
ok got it

**Comment by VFansss** [comment] 2021-01-30 20:48
GOG Version now shoudn't have this issue anymore.

Also, is now compatible with GOG Galaxy cloud.

**Closed** 2021-01-30 20:54 UTC
Labels: admin rights issue, bug
