### ISSUE TITLE
Steam Controller working like a charm.

### ISSUE THREAD

**Issue by w1lddog2** [VFansss/mgs2-v-s-fix#45] opened 2018-07-16 06:02 UTC
First of all, i want to thank you for this great fix for MGS2 PC port. The game plays like a charm.
Second this is not an issue at all, i just wanted to inform you, that your fix works perfectly with the Steam Controller.
Here is how you use a Steam Controller with MGS2 using your patch. After installing the patch you have to do the follow
1) Open MGS2SETUP.exe, go to Settings  - Controls and the set the 360 gamepad as NO.  Then to the "other" tab and set  "Open V´s Fix after playing" to Off.
2)Open Steam,  in the lower left of the windows there a " add game"  select "add a non steam product"
3)A new windows will open, go to folder where MGS2 is installed and select "mgs2_sse.exe".  It will add the game to the list of installed games.
4)Run the game and voila, you have a fully working steam overlay which will allow you to config the gamepad.

I made a layout it can be found in the community under "ID: 1442393756"  It works like PS2 layout and most important  the control stick is  pressure sensitive, which means you can walk and run without the need to press anything. Also you can quit the game using the steam overlay, instead of pressing ESC and then having to press accept in the small windows,  making it run quite seamless.

![20180716074321_1](https://user-images.githubusercontent.com/41280432/42744658-670b8a8a-88ce-11e8-8761-4f91fdb4bff6.jpg)

Control Stick Config so it works like a presure sensitive one.
![20180716074301_1](https://user-images.githubusercontent.com/41280432/42744673-79a7cf8c-88ce-11e8-9233-1f6c3cccb644.jpg)

![20180716074306_1](https://user-images.githubusercontent.com/41280432/42744676-7ff02f88-88ce-11e8-8017-a117f34032c3.jpg)

**Comment by VFansss** [comment] 2018-07-16 07:41
Oh, this is fantastic!

I don't have a Steam Controller so (like I've written on the fix Wiki) I have never been able to test it myself.

Unfortunately, I think there is still an issues with everything: can you please try to do that while enabling the anti-aliasing on the "Graphic tab" menu?

**Comment by Skryptonyte** [comment] 2018-07-16 10:20
In my experience, dpad, the face buttons, select and start and the right touchpad also function so you dont need to have them mapped to keys. Only the triggers and bumpers have problems for which you have to map them to keyboard controls.

**Comment by w1lddog2** [comment] 2018-07-16 12:05
With  anti-aliasing it works too,  here is the catch, this is something i do for other old games that need to compatibility mode/Admin rights to run for example the PC version of Alone in The Dark 4
Steam.exe by default doesn´t run as admin, in fact Valve says that shouldn't need to be run as one.  But if the program we are trying to run is executed as admin, then Steam won't be able to inject the overlay, because it lacks admin rights.
My "fix" is that i run Steam.exe as admin when i want to play those  games. I just tested mgs2sse.exe with anti-alias and if i run steam.exe without admin rights, no overlay.  Run with admin right, overlay for mgs2sse.exe.

**Comment by VFansss** [comment] 2018-07-17 09:31
Oh, thanks for reporting me that! I'm very happy with that, because now I've understand better not only how to make the Steam Controller compatible, but also how to make other controllers working through the Steam drivers.

> Steam.exe by default doesn´t run as admin, in fact Valve says that we shouldn't need to run it as one

And this is totally true. Unfortunately MGS2 have, because reasons. So we need to cope with that!

>  But if the program we are trying to run is executed as admin, then Steam won't be able to inject the overlay, because it will lacks admin rights.

Yup, exactly

> My "fix" is that i run Steam.exe as admin when i want to play those games. I just tested mgs2sse.exe with anti-alias and if i run steam.exe without admin rights, no overlay. 

You can also check the last post on the #18 Issue!

Sorry if I make a stupid question (I don't have a Steam controller!) but "no overlay" mean that, aside the overlay itself, the Steam Controller doesn't work, right?

> Run with admin right, overlay for mgs2sse.exe. Of you course is we don't use anti aliasing, then we don't need compatibility mode nor steam as admin.

Uhm...so if you disable the anti-aliasing...you don't need to start Steam like Admin to make the controller/overlay working?

Starting  Steam as admin isn't a fantastic solution, but obliviously is feasible. I've tried that in the past, but there is a popup that show up at every startup (Is in italian, but whatever!) :

![immagine](https://user-images.githubusercontent.com/15073502/42808728-30fd2e08-89b4-11e8-9160-c6a315c1accb.png)

But I saw that in the last updates of Steam you can check the checkbox to make it not show up anymore at startup, so isn't a bad things after all. Last time I've done it, that checkbox was missing, so the message ad EVERY startup was very annoying..

Aside that, this is a fantastic things to know!

Please check if the gamepad layout is working good, and every [special action](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#basic-actions) is feasible!

I would really like to include it inside the fix itself. I will work on a solution for that 👍 

I hope also to get my hands on a steam controller at a good price to try it out for myself how is working!

A last things: the vibration doesn't work, am I right? I hope there is still a chance to make it working...

**Comment by w1lddog2** [comment] 2018-07-17 14:34
> Uhm...so if you disable the anti-aliasing...you don't need to start Steam like Admin to make the controller/overlay working?> 
Exactly, if you disable anti-aliasing and don't run mgs2sse.exe as admin, then you don't need to run Steam as Admin.  The steam controller will work like it  should.


>Sorry if I make a stupid question (I don't have a Steam controller!) but "no overlay" mean that, aside the overlay itself, the Steam Controller doesn't work, right?>
Yes, if you have a shortcut in steam and the overlay is not showing it means that steam was not able to inject into the program.   Steam can only be injected in programs that use  apis Dx 7 to 12, OpenGL and Vulkan.
Fallout 1 , at least the version that's being sold in Steam renders in software mode, which means no Steam Controller.
If we try  to play the game with a keyboard and mouse, this is what we see.
![fallout](https://user-images.githubusercontent.com/41280432/42823258-6b7af118-89dd-11e8-98c3-b3a567979147.jpg)

Now, if we have the steam controller ON  we get a warning telling us, that the overlay is disable and some of the functions may not work (like the steam controller, take screenshot, etc).

![fallout controller](https://user-images.githubusercontent.com/41280432/42823316-926b81c0-89dd-11e8-8c08-237d00c71a7a.jpg)


> Please check if the gamepad layout is working good, and every special action is feasible!

A last things: the vibration doesn't work, am I right? I hope there is still a chance to make it working...>

Every Special action is feasible, in fact you can hae more "special actions" that can be used to cheat the game, for example turbo mode which can be used to cheat Solidus choke near the end of the game.

The only thing that doesn't work with the Steam Controller is the AP Sensor, since it requires vibration and the vibration is indeed not working.  The vibration featuer for the Steam Controller is still beta, in some games it "works"...  Sometimes the vibration will start but won't stop....

![20180717162620_1](https://user-images.githubusercontent.com/41280432/42824016-3f59e862-89df-11e8-8357-252c7028aa6d.jpg)

**Comment by w1lddog2** [comment] 2018-07-17 16:22
I think i found a work around for the Anti Aliasing and the admin rights.  I set the "bin" and "cdrom.img" folders  to be able to be modify by "ALL USER" in the security settings.  Now i can run Anti Aliasing no need for "xp compatibility" nor  admins rights.  Which means that now i can use Anti Aliasing and the steam controller at the same time.

**Comment by VFansss** [comment] 2018-07-24 20:35
>  I set the "bin" and "cdrom.img" folders to be able to be modify by "ALL USER" in the security settings.

It's what the 1.05.2 version of the fix is doing, but I don't think its working so good.

Just for info: what you are precisely editing to achieve that?

Because granting rights to the main folder and/or to each single file doesn't fix the "black screen" error you are talking about?

What are the precise actions you have done? 😄

**Comment by w1lddog2** [comment] 2018-07-25 01:05
I'm using 1.04, i just re-checked and it does show it as On, but is not.. My mistake

**Comment by VFansss** [comment] 2018-08-04 16:43
I will insert these informations inside the official Wiki.

Also, as soon as I can get my hands on a Steam Controller I will officially insert everything directly inside the fix.

Thanks again for all this works, I'm sure A LOT of people will appreciate that!

**Comment by ajojoreference** [comment] 2018-08-29 15:28
@VFansss You don't need a steam controller, I think the problem here is with the steam input configurator and its xinput emulation. You can try hooking up an xbox 360 controller and enabling configuration support for it in steams controller settings, and then launch it through steam as a non steams shortcut, with a xbox gamepad profile. I have a xbox gamepad that works perfectly (rumble and triggers work as intended) with this game and when I try playing it through steam using steam's input configuration it has the same problems as a regular steam controller.

**Comment by ajojoreference** [comment] 2018-08-29 15:45
Also @VFansss I think I might have found a good solution to this. Theres a tool called GloSC thats used for games that have issues with getting a steam overlay to work, so what the program does is create its own steam overlay that goes on top of the program. In addition to this it also uses a different form of xbox 360 controller emulation than steam which has better compatibility. I tried using it with this game and it seems like it might actually work well, the triggers and rumble work as intended. The only problem is that bindings are messed up and are all over the place (like in addition to LT and RT being the item windows, they're also bound to codec and start.) In addition the steam overlay doesn't work right since mgs2 isn't borderless

**Comment by VFansss** [comment] 2020-08-20 09:09
In the new 1.8 fix, you can select "Steam controller" from the "Controls tab".

I've also updated the wiki to better sort how to make it working.

This mean that the default keyboard layout necessary to use the @w1lddog2 button layout on Steam will be used, and that every compatibility option with Steam will be applied:

* Use FXAA instead of SMAA
* Turn "Open V's fix after playing" is set to OFF

I don't have a Steam controller, but if the game is added to Steam (manually of through the "Add2Steam" function from inside the fix) the layout should pop and work as intented.

It's the best I can do without external software.

I hope is enough.

Thanks again to @w1lddog2 for making this layout. Seems fantastic to have some kind of pressure buttons like the original. I have to test it one day.

I'm closing this issue, but I will pin it so it could be easily found in the future for any updates.

**Closed by VFansss** 2020-08-20 09:09 UTC
Labels: Input related, steam

**Comment by williamjcm** [comment] 2020-09-25 20:20
As of today, I can't find @w1lddog2's layout in the Controller Configuration screen.

I don't know if it's related to the name of the game in the Steam library (I used the tool's built-in feature to add the game to Steam) or something else, though.

**Comment by Adam-M93** [comment] 2020-10-21 21:29
I found that just with setting the gamepad to Steam Controller the controller works, but the button bindings are wrong like ajojoreference said, copying the contents of XB1 padbtn over fixes everything but the triggers and vibration, the keyboard keys can be bound to the triggers in Steam's Controller Config to get around that though, like this
![steam_2020-10-21_21-57-12](https://user-images.githubusercontent.com/8584772/96787236-4fad5780-13e9-11eb-839c-30866a5e0207.png)

Just incase, I'll repost the layouts from the XB padbtn
PS2 Layout
```
00  A
01  B
02  X
03  Y
04  L2
05  R2
06  SEL
07  STA
08  EX2
08  EX3
09  AR
0A  L1
0B  R1
```

V's Layout
```
00  A
01  B
02  X
03  Y
04  L2
05  EX3
05  AR
06  SEL
07  STA
08  EX2
09  EX1
0A  L1
0B  R1
```

The default padana that's set when picking the Steam Controller setting seemed fine for both left and right stick
```
00  Rx  N
01  Ry  N
02  X   N
03  Y   N
```

Haven't been able to test the sword, don't have a save near the end and when using the drebin cheat it's just stuck on raiden's back unusable, but the right pad does move the camera when against a wall at least

**Comment by w1lddog2** [comment] 2020-10-21 21:45
In anyone want my layout, here it is  steam://controllerconfig/952060/1442385536
