### ISSUE TITLE
Reshade?

### ISSUE THREAD

**Issue by TheKrzysiek** [VFansss/mgs2-v-s-fix#63] opened 2018-12-16 16:34 UTC
I tried installing it on both OpenGL and DirectX9 (with and without d3d8 fix) but so far nothing shows up in game. Any chance of _somehow_ getting it to work?

**Comment by VFansss** [comment] 2018-12-16 16:39
Try to disable wide-screen fix and anti-aliasing, if they are enabled.

The game already use the ENV Series dx8todx9 wrapper, but for the next version (is coming very soon) I've changedthe dx8todx9 wrapper to crosire's one, so I'm almost 99% sure that somehow is possible to use reshade.

I can't try it myself right now, but I will do as soon as I can....

**Comment by TheKrzysiek** [comment] 2018-12-16 18:12
Tried with it disabled and still didnt work for me, but its good to hear it might work with future version.

**Comment by VFansss** [comment] 2018-12-27 09:10
I can confirm that with the latest 1.7 version of the fix (NB: I haven't released it yet) all is working good.

The reshade installer detect that the game is a Dx8 game and prompt to install a Dx8toDx9 wrapper, but it isn't necessary because it's already included in the fix. 

![reshade](https://user-images.githubusercontent.com/15073502/50474017-984b8380-09bf-11e9-88dd-3458669e1822.jpg)

The fonts is a bit...funky, but I didn't investigated it further ( I already had this issue in the past, and probably is related to my config).

Now I can only say: please wait for the 1.7 release 😄

**Comment by TheKrzysiek** [comment] 2018-12-27 14:45
Nice!

**Comment by VFansss** [comment] 2018-12-27 18:36
I'm going to close this issue as to make it look like I've done an incredible and hard job (when in reality it's not so 😁) 

If you are facing some incredible issue when the 1.7 come out, please re-open it and we will further investigate on what's going on 😄

**Closed by VFansss** 2018-12-27 18:36 UTC
