### ISSUE TITLE
Defender Game Racer Turbo RS3 doesn't work properly

### ISSUE THREAD

**Issue by cafuneandchill** [VFansss/mgs2-v-s-fix#61] opened 2018-11-03 17:11 UTC
Hello!

I have a Defender Game Racer Turbo RS3 controller, which is a PS2-like controller. I used it before applying the Fix, and it was working perfectly, though it didn't have the rumble. I did use manually mapped controls.

Now, after applying the Fix, not only I don't still have the rumble, in "DualShock" mode X and O (thus, crouching and punching) are swapped, and also triggers and bumpers. Using X360CE in pair with "Xbox" mode didn't help.

I am out of ideas. Please help!

**Comment by VFansss** [comment] 2018-11-05 15:58
Hi! Sorry for the late reply!

> I used it before applying the Fix, and it was working perfectly, though it didn't have the rumble. I did use manually mapped controls.

Did you had the patience to do that yourself? 😄 

The issue is that the V's Fix is overwriting any previous gamepad and keyboard config, so is a kinda normal things. 

> Now, after applying the Fix, not only I don't still have the rumble,

The rumble can be re-enabled only on XInput gamepad, or gamepad that emulate Xinput driver through some software.

So only install the V's Fix isn't enough for the vibration!

You have to emulate an Xbox gamepad using X360CE or [Xoutput](https://github.com/csutorasa/XOutput), and hope that your controller is at least compliant with that!

> in "DualShock" mode X and O (thus, crouching and punching) are swapped

Don't use DualShock4 Mode! Buttons are very different from a PS2-like gamepad!

In fact is designed for DS4, and anything else.

> Using X360CE in pair with "Xbox" mode didn't help.

Strange!

Why you didn't succeed?

> I am out of ideas. Please help!

You can simply try select 'NO' from the Gamepad selection menu.

Even if isn't told anywhere, it should deploy a "basic" configuration that should be similar to a PS2-like gamepad.

Tell me if its working!

**Comment by cafuneandchill** [comment] 2018-11-06 17:16
> Using X360CE in pair with "Xbox" mode didn't help.

> Strange!

> Why you didn't succeed?

Don't really know, but using "Xbox" mode either with or without X360CE gives the same result - the buttons are messed up, in particular, the Crouch action is set on the Triangle button.

Maybe I'm messing up the actual X360CE setup? Would you please show me how to apply it properly to your fix?

> You can simply try select 'NO' from the Gamepad selection menu.

> Even if isn't told anywhere, it should deploy a "basic" configuration that should be similar to a PS2-like gamepad.

I did try that, though the right stick doesn't work if I do that, and also no rumble. Maybe triggers and bumpers were swapped as well, I don't remember correctly now.

The strangest part is, I have problems with other games when I try to set up the rumble via X360CE, and in result, the rumble is either too weak or doesn't even work every time. Maybe I should get a new controller...

**Comment by VFansss** [comment] 2018-11-08 09:46
> Don't really know, but using "Xbox" mode either with or without X360CE gives the same result - the buttons are messed up, in particular, the Crouch action is set on the Triangle button.

This make me thing that X360CE isn't working at all...

> Maybe I'm messing up the actual X360CE setup? 

It could be that X360 isn't working good...

An user has linked me [Xoutput](https://github.com/csutorasa/XOutput), that should be much more better and reliable. Try it out...

> I did try that, though the right stick doesn't work if I do that, and also no rumble.

The missing rumble is normal: the rumble is working ONLY if you restore xinput (= you enable xbox gamepad) AND your gamepad is a little compatible with it...

> The strangest part is, I have problems with other games when I try to set up the rumble via X360CE, and in result, the rumble is either too weak or doesn't even work every time.

...and this make me thing that it isn't a lot compatible.

> the right stick doesn't work if I do that,

If other things are working good, maybe worth a try to fix the right stick and maintain this solution.

> Would you please show me how to apply it properly to your fix?

The main problem with that is that I don't have a directinput gamepad, so I'm in trouble to explain how is working something I don't have.

The last time I tried X360CE was 10 years ago, and it worked in half, but it wasn't too hard to use.

I can't perfectly pin-point the right steps to perform for in this case 😢

**Comment by cafuneandchill** [comment] 2018-11-08 18:46
Ok, I'll check out Xoutput, and if it doesn't work, then I'll just get used to playing without rumble.
Thank you for the help! If Xoutput works, then I'll write here.

**Comment by cafuneandchill** [comment] 2018-11-10 18:39
Xoutput fixed some of the buttons, but it's still way far from perfect and still doesn't have rumble. Guess I'll be using it w/o vibration.

**Comment by VFansss** [comment] 2018-12-27 18:32
I've tried some old xinput gamepad using Xoutput and, after configuring them properly, they are working as intended. One of them has even the vibration working!

I can't properly say that there is something I still can do, aside update the Wiki with more details on how to install Xoutput and Vigem, so I'm closing this issue 😢 

If there is still something I can do, please tell me and we will figure it out 😄

**Closed by VFansss** 2018-12-27 18:32 UTC
Labels: Gamepads related
